name: aero
description: "A new Flutter project."

publish_to: 'none'

version: 1.5.1+7

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2 
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/header.png
    - assets/images/logo_icon.png
    - assets/images/logo_text_dark.png
    - assets/images/logo_text_dark@2x.png
    - assets/images/logo_text_dark@3x.png
    - assets/images/logo_text_light.png
    - assets/images/logo_text_light@2x.png
    - assets/images/logo_text_light@3x.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon.png"
  adaptive_icon_background: "#FAFAFA"
  adaptive_icon_foreground: "assets/images/logo_icon.png"
